# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-20 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_de_mission', models.DateField(blank=True)),
                ('horaire_debut', models.TimeField(blank=True)),
                ('horaire_fin', models.TimeField(blank=True)),
                ('is_client_visible', models.BooleanField(default=False)),
                ('is_misson_type_visible', models.BooleanField(default=False)),
                ('is_adresse_visible', models.BooleanField(default=False)),
                ('adresse_de_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.Adresse_client')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.Client')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.Profile_consultant')),
                ('mission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.Mission_type_client')),
                ('piece_jointe', models.ManyToManyField(blank=True, related_name='piece_jointe', to='planning.Piece_jointe_client')),
                ('piece_jointe_visible', models.ManyToManyField(blank=True, related_name='piece_jointe_visible', to='planning.Piece_jointe_client')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.Statut_mission')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Mission',
            },
        ),
    ]
