# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-21 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20200320_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_consultant',
            name='code_postal',
            field=models.CharField(default='N-A', max_length=100),
        ),
        migrations.AddField(
            model_name='profile_consultant',
            name='ville',
            field=models.CharField(default='N-A', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile_consultant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
