# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-21 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_auto_20200321_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_consultant',
            name='code_postal',
        ),
    ]
