# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_remove_profile_consultant_code_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_consultant',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar'),
        ),
    ]
