# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-21 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0007_profile_consultant_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdd_messages',
            name='envoyeur',
        ),
        migrations.RemoveField(
            model_name='bdd_messages',
            name='receveur',
        ),
        migrations.AddField(
            model_name='bdd_messages',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bdd_messages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
