# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-21 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0008_auto_20200321_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_administrateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar/default.png', upload_to='avatar')),
                ('archive', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_administrateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Consultant',
                'ordering': ['id'],
            },
        ),
    ]
