# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-22 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_profile_administrateur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_administrateur',
            options={'ordering': ['id'], 'verbose_name': 'Profile Administrateur'},
        ),
        migrations.AddField(
            model_name='profile_consultant',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
