# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-24 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_auto_20200324_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='date_modification',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
