# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-27 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_remove_profile_consultant_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_consultant',
            name='code_postal',
            field=models.CharField(default='N-A', max_length=20),
        ),
    ]
