# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_profile_consultant_code_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.CharField(default='N-A', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(default='N-A', max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='adresse_de_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.Adresse_client'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.Client'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.Profile_consultant'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.Mission_type_client'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.Statut_mission'),
        ),
    ]
