# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-28 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0020_client_site_web'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='mail',
            new_name='email',
        ),
    ]
