# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-28 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0021_auto_20200328_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse_client',
            name='favori',
            field=models.BooleanField(default=False),
        ),
    ]
