# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-28 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0022_adresse_client_favori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece_jointe_client',
            old_name='is_favorite',
            new_name='favori',
        ),
        migrations.AddField(
            model_name='mission_type_client',
            name='favori',
            field=models.BooleanField(default=False),
        ),
    ]
