# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-29 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0023_auto_20200328_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission_type_client',
            name='date_upload',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
