# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-30 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0024_mission_type_client_date_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_consultant',
            new_name='Profile_user',
        ),
    ]
