# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-31 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0026_auto_20200330_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_administrateur',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='profile_user',
            options={'ordering': ['id'], 'verbose_name': 'Profile'},
        ),
        migrations.AlterField(
            model_name='mission',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile_administrateur',
        ),
    ]
