# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-31 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0029_auto_20200331_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
