# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-31 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0030_auto_20200331_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_user',
            name='dernier_message',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
