# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-31 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0043_profile_user_couleur_rdm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_user',
            name='couleur_rdm',
            field=models.CharField(blank=True, choices=[('#5578eb', '#5578eb'), ('#1dc9b7', '#1dc9b7'), ('#ff0000', '#ff0000'), ('#ff8f00', '#ff8f00'), ('#ffed00', '#ffed00')], max_length=20),
        ),
    ]
