# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-04-01 19:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0045_auto_20200401_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jour_bloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero_jour', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('est_bloque', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Jours bloqué',
                'ordering': ['nom'],
            },
        ),
    ]
