# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-04-01 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0047_contrat_jour_annee_bloque_jour_mission_jour_semaine_bloque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_rendu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='N-A', max_length=50)),
                ('document', models.FileField(blank=True, upload_to='piece_jointe_rendu/')),
                ('date_upload', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documents rendu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document_supplementaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='N-A', max_length=50)),
                ('document', models.FileField(blank=True, upload_to='piece_jointe_supplementaire/')),
                ('date_upload', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documents supplémentaire',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['contrat'], 'verbose_name': 'Mission'},
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='adresse_de_mission',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='piece_jointe',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='consultant',
            new_name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='client',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='horaire_debut',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='horaire_fin',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='is_adresse_visible',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='is_client_visible',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='is_misson_type_visible',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='jour_de_mission',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='piece_jointe_visible',
        ),
        migrations.AddField(
            model_name='mission',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.Contrat'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.Statut_contrat'),
        ),
        migrations.AddField(
            model_name='document_supplementaire',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.Mission'),
        ),
        migrations.AddField(
            model_name='document_rendu',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.Mission'),
        ),
    ]
