# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-04-01 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0048_auto_20200402_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jour_bloque',
        ),
    ]
