# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-04-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0050_remove_jour_semaine_bloque_est_recurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jour_bloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Jours bloqué',
            },
        ),
        migrations.CreateModel(
            name='Jour_semaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Jours semaine',
                'ordering': ['nom'],
            },
        ),
        migrations.DeleteModel(
            name='Jour_semaine_bloque',
        ),
        migrations.AlterModelOptions(
            name='jour_annee_bloque',
            options={'ordering': ['date'], 'verbose_name': 'Jours année bloqué'},
        ),
        migrations.RemoveField(
            model_name='jour_annee_bloque',
            name='est_bloque',
        ),
        migrations.RemoveField(
            model_name='jour_annee_bloque',
            name='nom',
        ),
        migrations.AddField(
            model_name='jour_bloque',
            name='jour_semaine',
            field=models.ManyToManyField(blank=True, to='planning.Jour_semaine'),
        ),
        migrations.AddField(
            model_name='jour_annee_bloque',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.Jour_bloque'),
        ),
    ]
