# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-04-02 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0051_auto_20200402_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jour_mission',
            name='mission',
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['jour_de_mission'], 'verbose_name': 'Missions jour'},
        ),
        migrations.AddField(
            model_name='mission',
            name='heure_debut',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='heure_fin',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='jour_de_mission',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Jour_mission',
        ),
    ]
